 "use client";
import {useEffect,useState} from "react"; import {createClient} from "@/lib/supabase-browser";
export default function Admin(){const supabase=createClient();const [user,setUser]=useState(null);const [products,setProducts]=useState([]);const [form,setForm]=useState({name:"",price:"",stock:"",category:"Mobile",description:"",video_url:"",image_url:""});const [editing,setEditing]=useState(null);const [msg,setMsg]=useState("");
useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user));load();},[]);
async function load(){const {data}=await supabase.from("products").select("*").order("created_at",{ascending:false});if(data)setProducts(data);}
async function save(e){e.preventDefault();setMsg("");let payload={...form,price:Number(form.price),stock:Number(form.stock)};let r=editing?await supabase.from("products").update(payload).eq("id",editing):await supabase.from("products").insert(payload);if(r.error)setMsg(r.error.message);else{setMsg("Saved");setEditing(null);setForm({name:"",price:"",stock:"",category:"Mobile",description:"",video_url:"",image_url:""});load();}}
async function del(id){if(!confirm("Delete this product?"))return;await supabase.from("products").delete().eq("id",id);load();}
function edit(p){setEditing(p.id);setForm(p);}
if(!user)return <div className="shell pagePad"><h1>Admin</h1><p>Login first.</p><a className="btn" href="/auth">Login</a></div>;
return <div className="shell pagePad"><div className="adminHead"><div><p className="eyebrow">PRIVATE CONTROL CENTER</p><h1>Admin dashboard</h1></div><a href="/" className="btn secondaryBtn">Storefront</a></div><div className="stats"><div><b>{products.length}</b><span>Products</span></div><div><b>{products.reduce((a,p)=>a+(p.stock||0),0)}</b><span>Total stock</span></div><div><b>∞</b><span>Manage everything</span></div></div><div className="adminGrid"><form className="panel form" onSubmit={save}><h2>{editing?"Edit product":"Add product"}</h2><input required placeholder="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="number" placeholder="Price" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input required type="number" placeholder="Stock" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["Mobile","Laptop","Audio","Power","Cables","Desk Setup"].map(x=><option key={x}>{x}</option>)}</select><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder="Product image URL (Supabase Storage later)" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/><input placeholder="Product demo video URL" value={form.video_url} onChange={e=>setForm({...form,video_url:e.target.value})}/><button className="btn">{editing?"Update product":"Add product"}</button>{editing&&<button type="button" className="btn secondaryBtn" onClick={()=>{setEditing(null);setForm({name:"",price:"",stock:"",category:"Mobile",description:"",video_url:"",image_url:""})}}>Cancel</button>}{msg&&<p>{msg}</p>}</form><div className="panel"><h2>Products</h2><div className="adminList">{products.map(p=><div className="adminItem" key={p.id}><div><b>{p.name}</b><small>₹{p.price} • Stock {p.stock} • {p.category}</small>{p.video_url&&<small>🎥 Video enabled</small>}</div><div><button onClick={()=>edit(p)}>Edit</button><button onClick={()=>del(p.id)}>Delete</button></div></div>)}</div></div></div></div>}
